# Generated by Django 2.2.12 on 2021-02-01 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userId',
            field=models.IntegerField(),
        ),
    ]
