# Generated by Django 2.2.12 on 2021-02-01 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210201_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userPerm',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
