# Generated by Django 2.2.12 on 2021-02-01 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_meter'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='owner',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserMeter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Meter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Meter')),
            ],
        ),
    ]
