# Generated by Django 2.2.12 on 2021-02-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210201_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='value',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
