# Generated by Django 2.2.12 on 2021-02-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_reading_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reading',
            name='time',
            field=models.TimeField(default=1),
            preserve_default=False,
        ),
    ]
