# Generated by Django 2.2.12 on 2021-02-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210201_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='time',
            field=models.TimeField(blank=True),
        ),
    ]
