# Generated by Django 2.2.12 on 2021-02-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210201_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='date',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='reading',
            name='time',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
